name: Compile Latex and Release PDF

on:
  push: { branches: ["master", "main"] }
  workflow_dispatch:

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex

      - name: Upload
        uses: actions/upload-artifact@master
        with:
          name: ./
          path: ./
        if: always()
